Using the images marked as valid per cluster, we pass them through the CNN and extract their feature vectors. the results are stored at a per-country basis. For example, all Malawi feature extractions will go into results/malawi_2016/cnn.

In [1]:
import os
import shutil
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm
import pickle

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import copy

In [15]:
BASE_DIR = '..'
# COUNTRIES_DIR = os.path.join(BASE_DIR, 'data', 'countries')
# PROCESSED_DIR = os.path.join(BASE_DIR, 'data', 'processed')
# RESULTS_DIR = os.path.join(BASE_DIR, 'results')
CNN_IMAGE_DIR = os.path.join(BASE_DIR, 'images')
CNN_DIR = os.path.join(BASE_DIR, 'models', 'trained_model.pt')

In [4]:
# os.makedirs(RESULTS_DIR, exist_ok=True)
# for country in ['malawi_2016', 'ethiopia_2015', 'nigeria_2015']:
#     os.makedirs(os.path.join(RESULTS_DIR, country), exist_ok=True)

# Feature extract with CNN
If you have run this step before, you can skip it and run the commented out code in the next section to quick-start.

In [5]:
# df_images = pd.read_csv(os.path.join(PROCESSED_DIR, 'image_download_actual.csv'))

In [7]:
# df_images.head()

image_name  image_lat  image_lon  \
0  -17.09515_35.17229723579403_-17.09515_35.21721... -17.095150  35.172297   
1  -17.08017807859801_35.17229723579403_-17.09515... -17.080178  35.172297   
2  -17.125093842803985_35.18726915719602_-17.0951... -17.125094  35.187269   
3  -17.140065764205975_35.20224107859801_-17.0951... -17.140066  35.202241   
4  -17.065206157196016_35.20224107859801_-17.0951... -17.065206  35.202241   

   cluster_lat  cluster_lon   cons_pc  nightlights country  nightlights_bin  \
0    -17.09515    35.217213  1.423239     0.025206      mw                0   
1    -17.09515    35.217213  1.423239     0.025206      mw                0   
2    -17.09515    35.217213  1.423239     0.025206      mw                0   
3    -17.09515    35.217213  1.423239     0.025206      mw                0   
4    -17.09515    35.217213  1.423239     0.025206      mw                0   

   is_train  
0      True  
1      True  
2     False  
3      True  
4      True

In [6]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using {device} as backend')
model = torch.load(CNN_DIR, map_location=device)

Using cpu as backend


In [7]:
model.classifier

Sequential(
  (0): Linear(in_features=25088, out_features=4096, bias=True)
  (1): ReLU(inplace=True)
  (2): Dropout(p=0.5, inplace=False)
  (3): Linear(in_features=4096, out_features=4096, bias=True)
  (4): ReLU(inplace=True)
  (5): Dropout(p=0.5, inplace=False)
  (6): Linear(in_features=4096, out_features=3, bias=True)
)

In [8]:
# rip off the final layers
model.classifier = model.classifier[:4]

In [9]:
model.classifier

Sequential(
  (0): Linear(in_features=25088, out_features=4096, bias=True)
  (1): ReLU(inplace=True)
  (2): Dropout(p=0.5, inplace=False)
  (3): Linear(in_features=4096, out_features=4096, bias=True)
)

In [27]:
transformer = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])

# custom dataset for fast image loading and processing
# does not follow the usual style of folder -> folder for each class -> image
# we just want one folder with images
class ForwardPassDataset(torch.utils.data.Dataset):
    def __init__(self, image_dir, transformer):
        self.image_dir = image_dir
        self.image_list = os.listdir(self.image_dir)
        self.transformer = transformer

    def __len__(self):
        return len(self.image_list)

    def __getitem__(self, index):
        image_name = self.image_list[index]

        # Load image
        X = self.filename_to_im_tensor(self.image_dir + '/' + image_name)
        
        # dataloaders need to return a label, but for the forward pass we don't really care
        return X, -1
    
    def filename_to_im_tensor(self, file):
        im = plt.imread(file)[:,:,:3]
        im = self.transformer(im)
        return im

model.eval()  
classes = [0, 1, 2]
# shape of final array will be (num_validation_images, 4096)
# we also want to record the image each index represents
feats = np.zeros((1000, 4096))
image_order = []
i = 0
# for c in classes:
    # use the validation images to do the forward pass
dataset = ForwardPassDataset(os.path.join(CNN_IMAGE_DIR, 'ward_1', 'edited'), transformer)
dataloader = torch.utils.data.DataLoader(dataset, batch_size=8, shuffle=False, num_workers=4)
image_order += dataset.image_list
# forward pass for this class
for inputs, _ in tqdm(dataloader):
    inputs = inputs.to(device)
    outputs = model(inputs)
    print(outputs)
#     feats[i:i+len(inputs),:] = outputs.cpu().detach().numpy()
#     i += len(inputs)

tensor([[-0.7783,  1.1016, -0.1959,  ...,  0.0427,  0.0952, -1.1975],
        [-0.7034,  0.1166, -0.1621,  ...,  0.1045,  1.0096, -0.9460],
        [-1.3177, -0.0722, -0.3931,  ...,  0.0484,  0.1903, -1.2159],
        ...,
        [-0.0515, -0.4898,  0.3363,  ...,  0.1145,  0.0422, -0.6688],
        [-0.1311, -0.1404,  0.0806,  ...,  0.6589, -0.0551, -1.0909],
        [-1.2350,  0.0265,  0.2964,  ...,  0.4178,  0.9953, -1.6981]],
       grad_fn=<AddmmBackward>)
tensor([[-2.5550, -0.2291,  0.3078,  ..., -0.0287,  0.4799, -2.0992],
        [-1.6506, -0.1278,  0.3161,  ...,  0.3962, -0.3737, -1.4776],
        [-2.0778, -0.4005,  0.0263,  ...,  1.0800,  0.0548, -1.8931],
        ...,
        [-0.7049, -0.6875,  0.8751,  ..., -0.6134,  0.4951, -0.3611],
        [-1.2870, -0.6103,  0.7389,  ...,  0.2399,  0.6828, -1.1949],
        [-1.5025, -0.2589, -0.0039,  ...,  0.4699,  0.6253, -1.6142]],
       grad_fn=<AddmmBackward>)
tensor([[-1.4995, -0.1818,  0.0358,  ...,  0.2018,  0.4279, -1.3771]

In [25]:
dataset.image_list

['00.png',
 '01.png',
 '02.png',
 '03.png',
 '04.png',
 '05.png',
 '10.png',
 '11.png',
 '12.png',
 '13.png',
 '14.png',
 '15.png',
 '20.png',
 '21.png',
 '22.png',
 '23.png',
 '24.png',
 '25.png',
 '30.png',
 '31.png',
 '32.png',
 '33.png',
 '34.png',
 '35.png']

In [13]:
feats

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [36]:
forward_pass_df = pd.DataFrame.from_dict({'image_name': image_order, 'feat_index': np.arange(len(image_order))})
forward_pass_df.head()

image_name  feat_index
0  10.513181862198008_39.768191057994024_10.52815...           0
1  -14.632534157196016_34.981995235794024_-14.662...           1
2  -14.526346764205977_35.593520078598004_-14.481...           2
3  7.4290196173360155_7.26950147266_7.45896346014...           3
4  -10.405547698244352_34.14279535535209_-10.4038...           4

In [37]:
df_consumption = pd.merge(left=df_images, right=forward_pass_df, on='image_name')

In [40]:
# have we maintained all validation images?
assert len(df_consumption) == (~df_images['is_train']).sum()

In [41]:
df_consumption.head()

image_name  image_lat  image_lon  \
0  -17.125093842803985_35.18726915719602_-17.0951... -17.125094  35.187269   
1  -17.140065764205975_35.232184921401995_-17.095... -17.140066  35.232185   
2  -17.065206157196016_35.262128764205976_-17.095... -17.065206  35.262129   
3  -17.07737907859801_35.069727235794026_-17.0923... -17.077379  35.069727   
4  -17.137266764205975_35.08469915719602_-17.0923... -17.137267  35.084699   

   cluster_lat  cluster_lon   cons_pc  nightlights country  nightlights_bin  \
0   -17.095150    35.217213  1.423239     0.025206      mw                0   
1   -17.095150    35.217213  1.423239     0.025206      mw                0   
2   -17.095150    35.217213  1.423239     0.025206      mw                0   
3   -17.092351    35.114643  1.266204     0.000000      mw                0   
4   -17.092351    35.114643  1.266204     0.000000      mw                0   

   is_train  feat_index  
0     False         318  
1     False        1861  
2     False         836  
3     False          18  
4     False        1051

## Aggregate Features
For each country, we aggregate the image features per cluster and save them to results/country/cnn

In [47]:
country_abbrv = ['mw', 'eth', 'ng']
country_dir = ['malawi_2016', 'ethiopia_2015', 'nigeria_2015']

for ca, cd in zip(country_abbrv, country_dir):
    df_c = df_consumption[df_consumption['country'] == ca]
    group = df_c.groupby(['cluster_lat', 'cluster_lon'])
    x = np.zeros((len(group), 4096))
    cluster_list = [] # the corresponding clusters (lat, lon) to the x aggregate feature array
    for i, g in enumerate(group):
        lat, lon = g[0]
        im_sub = df_consumption[(df_consumption['cluster_lat'] == lat) & (df_consumption['cluster_lon'] == lon)].reset_index(drop=True)
        agg_feats = np.zeros((len(im_sub), 4096))
        for j, d in im_sub.iterrows():
            agg_feats[j,:] = feats[d.feat_index]
        agg_feats = agg_feats.mean(axis=0) # averages the features across all images in the cluster

        x[i,:] = agg_feats
        cluster_list.append([lat, lon])
    # save to the correct directory
    save_dir = os.path.join(RESULTS_DIR, cd, 'cnn')
    os.makedirs(save_dir, exist_ok=True)
    np.save(os.path.join(save_dir, 'cluster_feats.npy'), x)
    pickle.dump(cluster_list, open(os.path.join(save_dir, 'cluster_order.pkl'), 'wb')) 
    